import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./home/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "School Management application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      {/* <Home/> */}
      </body>
    </html>
  );
}
